databases:
  - name: rankme7000-db
    plan: free
    databaseName: rankme7000
    user: rankme7000

services:
  - type: web
    name: rank-me-7000
    plan: free
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build && npm run db:seed:prod
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rankme7000-db
          property: connectionString
      - key: NODE_ENV
        value: production
